name: Fetch Appstore Info 

on:
 schedule:
     - cron: "0/20 * * * *"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js "14.x"
        uses: actions/setup-node@v2.1.1
        with:
          node-version: "14.x"
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"
      - run: gem install bundler:2.1.4
      - run: bundle install
      - run: npm install 
      - run: node Sources/check_status.js
        env: 
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          KEY_ID: ${{ secrets.KEY_ID }}
          ISSUER_ID: ${{ secrets.ISSUER_ID }}
          BUNDLE_ID: ${{ secrets.BUNDLE_ID }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          LANGUAGE: "en"
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'  
      - name: push
        uses: github-actions-x/commit@v2.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'Store Appstore Info'
          force-add: 'true'
          files: store.db
          name: hj
          email: hee6542000@hanmail.net
